[package]
authors = ["fun4wut <nihouze@163.com>"]
edition = "2018"
name = "webserver"
version = "0.1.0"

[dependencies]
async-std = {version = "0.99", features = ["unstable"]}
futures-timer = "1.0"
scheduled-thread-pool = "0.2.2"
crossbeam = "0.7"
